apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-deployment
  labels:
    app: demoapp-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demoapp-service
  template:
    metadata:
      labels:
        app: demoapp-service
    spec:
      nodeSelector:
        nodeType: cpu-node
      tolerations:
      - effect: "NoSchedule"
        key: "cpuIntensive"
        operator: "Equal"
        value: "true"
      containers:
      - name: demoapp-service
        image: kustomization-eks-repository
        imagePullPolicy: Always
        ports:
        - containerPort: 8100
        resources:
          requests:
            cpu: 1
            memory: 4000Mi
      restartPolicy: Always

